src/Entity/SiFile.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SiFileRepository")
 * @Vich\Uploadable()
 */
class SiFile
{

    const FILE_TYPE = [
        'cover' => 1,  // used on the top of the show
        'logo' => 2,   // logo shared by multiple shows
        'editionPicture' => 3,  // picture illustrating the edition
        'contentPicture' => 4,  // picture displayed inside the content, can be multiple
        'thumbnail' => 5,
        'carouselPicture' => 6  // ude to illustrate show with a small squared picture"
    ];


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="Uploaded_file", fileNameProperty="mediaFileName")
     * @Assert\NotBlank
     */
    private $mediaFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $mediaFileName;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Content", mappedBy="logos")
     */
    private $logoContents;

     /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Edition", mappedBy="editionPicture", cascade={"persist", "remove"})
     */
    private $edition;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Content", inversedBy="pictures")
     */
    private $pictureContent;


    public function __construct()
    {
        $this->logoContents = new ArrayCollection();
    }

    /**
     * returns the key linkd to the value of the filetype const
     * @return string
     */
    public function getFileTypeName():string
    {
        return array_search($this->type, self::FILE_TYPE);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Content[]
     */
    public function getLogoContents(): Collection
    {
        return $this->logoContents;
    }

    public function addLogoContent(Content $logoContent): self
    {
        if (!$this->logoContents->contains($logoContent)) {
            $this->logoContents[] = $logoContent;
            $logoContent->addLogo($this);
        }

        return $this;
    }

    public function removeLogoContent(Content $logoContent): self
    {
        if ($this->logoContents->contains($logoContent)) {
            $this->logoContents->removeElement($logoContent);
            $logoContent->removeLogo($this);
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getMediaFile(): ?File
    {
        return $this->mediaFile;
    }

    /**
     * @param File|null $mediaFile
     * @return SiFile
     */
    public function setMediaFile(?File $mediaFile): SiFile
    {
        $this->mediaFile = $mediaFile;

        // Only change the updated at if the file is really uploaded to avoid database updates.
        // This is needed when the file should be set when loading the entity.
        if ($this->mediaFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getMediaFileName(): ?string
    {
        return $this->mediaFileName;
    }

    /**
     * @param string|null $mediaFileName
     * @return SiFile
     */
    public function setMediaFileName(?string $mediaFileName): SiFile
    {
        $this->mediaFileName = $mediaFileName;

        // Only change the updated at if the file is really uploaded to avoid database updates.
        // This is needed when the file should be set when loading the entity.
        if ($this->mediaFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }


    /**
     * @return \DateTimeInterface
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * @param mixed $updatedAt
     * @return SiFile
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    public function getEdition(): ?Edition
    {
        return $this->edition;
    }

    public function setEdition(?Edition $edition): self
    {
        $this->edition = $edition;

        // set (or unset) the owning side of the relation if necessary
        $newEditionPicture = $edition === null ? null : $this;
        if ($newEditionPicture !== $edition->getEditionPicture()) {
            $edition->setEditionPicture($newEditionPicture);
        }

        return $this;
    }

    public function getPictureContent(): ?Content
    {
        return $this->pictureContent;
    }

    public function setPictureContent(?Content $pictureContent): self
    {
        $this->pictureContent = $pictureContent;

        return $this;
    }
}

src/Form/SiFileType.php
<?php

namespace App\Form;

use App\Entity\SiFile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

/**
 * Form used in order to have a complete form
 */
class SiFileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')

            ->add('type', ChoiceType::class, [
                'choices' => SiFile::FILE_TYPE
            ])
            ->add('mediaFile', VichFileType::class, [
                'required' => false,
                'download_uri' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SiFile::class,
        ]);
    }
}

templates/si_file/_delete_form.html.twig
<form method="post" action="{{ path('sifile_delete', {'id': si_file.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ si_file.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/si_file/_form.html.twig
{{ form_start(formFile) }}

    <div class="row">
        <div class="col-4">
            {{ form_label(formFile.name, "Nom du fichier") }}
            {{ form_widget(formFile.name) }}
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            {{ form_label(formFile.type) }}
            {{ form_widget(formFile.type) }}
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            {{ form_label(formFile.mediaFile) }}
            {{ form_widget(formFile.mediaFile) }}
        </div>
    </div>

    <button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(formFile) }}

templates/si_file/edit.html.twig
{% extends 'adminBase.html.twig' %}

{% block title %}Edit SiFile{% endblock %}

{% block body %}
    <h1>Editer un fichier</h1>

    {{ include('si_file/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('sifile_index') }}">Retour</a>

    {{ include('si_file/_delete_form.html.twig') }}
{% endblock %}

templates/si_file/index.html.twig
{% extends 'adminBase.html.twig' %}


{% block body %}
    <div class="title px-4 pb-4 pt-2">
    <h1>Liste des fichiers</h1>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Type</th>
                <th>Fichier</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for si_file in si_files %}
            <tr>
                <td>{{ si_file.name }}</td>
                <td>{{ si_file.fileTypeName }}</td>
                <td>
                    <img alt="img_fichier" src="/upload/file/{{ si_file.mediaFileName }}" style="width: 200px; height: auto" />
                </td>
                <td>
                    <a href="{{ path('sifile_show', {'id': si_file.id}) }}">Voir</a>
                    <a href="{{ path('sifile_edit', {'id': si_file.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun fichier enregistré</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('sifile_new') }}">Nouveau</a>

{% endblock %}

templates/si_file/new.html.twig
{% extends 'adminBase.html.twig' %}

{% block title %}New SiFile{% endblock %}

{% block body %}
    <h1>Nouveau fichier</h1>

    {{ include('si_file/_form.html.twig') }}

    <a href="{{ path('sifile_index') }}">Retour</a>

{% endblock %}

templates/si_file/show.html.twig
{% extends 'adminBase.html.twig' %}

{% block title %}SiFile{% endblock %}

{% block body %}
    <h1>Fichier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ si_file.name }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ si_file.type }}</td>
            </tr>
            <tr>
                <th>Fichier</th>
                <td>
                    <img alt="img_fichier" src="/upload/file/{{ si_file.mediaFileName }}" style="width: 400px; height: auto" />
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('sifile_index') }}">Retour</a>

    <a href="{{ path('sifile_edit', {'id': si_file.id}) }}">Modifier</a>

    {{ include('si_file/_delete_form.html.twig') }}
{% endblock %}