src/Entity/Content.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContentRepository")
 */
class Content
{
    const CONTENT_TYPE = [
        'festival' => 1,
        'actualités' => 2,
        'static_page' => 3,
        'hors scène' => 4,
        'tournée' => 5
    ];

    /**
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titleFr;

    /**
      * @ORM\Column(type="integer")
      */
    private $contentType;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titleEn;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contentFr;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contentEn;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $countryFr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $countryEn;

    /**
    * @ORM\ManyToOne(targetEntity="App\Entity\Edition", inversedBy="contents")
    */
    private $edition;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Session", mappedBy="content", orphanRemoval=true)
     */
    private $sessions;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\SiFile", inversedBy="logoContents")
     */
    private $logos;

    /**
     * @ORM\Column(type="boolean")
     */
    private $complete = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $translated = false;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SiFile", cascade={"persist", "remove"})
     */
    private $cover;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SiFile", cascade={"persist", "remove"})
     */
    private $thumbnail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SiFile", mappedBy="pictureContent",cascade={"persist"})
     */
    private $pictures;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Content", inversedBy="isEcho")
     */
    private $enEcho;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Content", mappedBy="enEcho")
     */
    private $isEcho;

    /**
     * @ORM\Column(type="boolean")
     */
    private $archive = false;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lieu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $director;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Theme", mappedBy="contents")
     */
    private $themes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $topArticle;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SiFile", cascade={"persist", "remove"})
     */
    private $carouselPicture;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->logos = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->enEcho = new ArrayCollection();
        $this->isEcho = new ArrayCollection();
        $this->themes = new ArrayCollection();
    }

    public function __toString():string
    {
        return array_search($this->getContentType(), self::CONTENT_TYPE)."-".$this->getTitleFr();
    }

    /**
    * returns the key linked to the value of the contentType const
    * @return string
    */
    public function getContentTypeName():string
    {
        return array_search($this->contentType, self::CONTENT_TYPE);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getTitleFr(): ?string
    {
        return $this->titleFr;
    }

    public function setTitleFr(string $titleFr): self
    {
        $this->titleFr = $titleFr;
        return $this;
    }

    public function getTitleEn(): ?string
    {
        return $this->titleEn;
    }

    public function setTitleEn(?string $titleEn): self
    {
        $this->titleEn = $titleEn;
        return $this;
    }

    public function getContentFr(): ?string
    {
        return $this->contentFr;
    }

    public function setContentFr(?string $contentFr): self
    {
        $this->contentFr = $contentFr;

        return $this;
    }

    public function getContentEn(): ?string
    {
        return $this->contentEn;
    }

    public function setContentEn(?string $contentEn): self
    {
        $this->contentEn = $contentEn;
        return $this;
    }

    public function getContentType(): ?int
    {
        return $this->contentType;
    }

    public function setContentType(int $contentType): self
    {
        $this->contentType = $contentType;

        return $this;
    }

    public function getCountryFr(): ?string
    {
        return $this->countryFr;
    }

    public function setCountryFr(?string $countryFr): self
    {
        $this->countryFr = $countryFr;
        return $this;
    }

    public function getCountryEn(): ?string
    {
        return $this->countryEn;
    }

    public function setCountryEn(?string $countryEn): self
    {
        $this->countryEn = $countryEn;
        return $this;
    }

    public function getEdition(): ?Edition
    {
        return $this->edition;
    }

    public function setEdition(?Object $edition): self
    {
        if ($edition instanceof Edition) {
            $this->edition = $edition;
        }
        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->setContent($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            // set the owning side to null (unless already changed)
            if ($session->getContent() === $this) {
                $session->setContent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|SiFile[]
     */
    public function getLogos(): Collection
    {
        return $this->logos;
    }

    public function addLogo(Object $logo): self
    {
        if (!$this->logos->contains($logo)) {
            $this->logos[] = $logo;
        }

        return $this;
    }

    public function removeLogo(SiFile $logo): self
    {
        if ($this->logos->contains($logo)) {
            $this->logos->removeElement($logo);
        }

        return $this;
    }

    public function getComplete(): ?bool
    {
        return $this->complete;
    }

    public function setComplete(bool $complete): self
    {
        $this->complete = $complete;

        return $this;
    }

    public function getTranslated(): ?bool
    {
        return $this->translated;
    }

    public function setTranslated(bool $translated): self
    {
        $this->translated = $translated;

        return $this;
    }

    public function getCover(): ?SiFile
    {
        return $this->cover;
    }

    public function setCover(?Object $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getThumbnail(): ?SiFile
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?Object $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    /**
     * @return Collection|SiFile[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Object $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setPictureContent($this);
        }

        return $this;
    }

    public function removePicture(SiFile $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getPictureContent() === $this) {
                $picture->setPictureContent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getEnEcho(): Collection
    {
        return $this->enEcho;
    }

    public function addEnEcho(self $enEcho): self
    {
        if (!$this->enEcho->contains($enEcho)) {
            $this->enEcho[] = $enEcho;
        }

        return $this;
    }

    public function removeEnEcho(self $enEcho): self
    {
        if ($this->enEcho->contains($enEcho)) {
            $this->enEcho->removeElement($enEcho);
        }

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getIsEcho(): Collection
    {
        return $this->isEcho;
    }

    public function addIsEcho(self $isEcho): self
    {
        if (!$this->isEcho->contains($isEcho)) {
            $this->isEcho[] = $isEcho;
            $isEcho->addEnEcho($this);
        }

        return $this;
    }

    public function removeIsEcho(self $isEcho): self
    {

src/Controller/UserContentController.php
<?php

namespace App\Controller;

use App\Repository\TarifRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Content;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\ContentRepository;
use App\Repository\SiFileRepository;
use App\Form\ContactType;

class UserContentController extends AbstractController
{
    /**
     * @Route("/content/{slug}", name="show_content", methods={"GET"})
     */
    public function showContent(Content $content, TarifRepository $tarifRepository): Response
    {
        return $this->render('UserTemplate/userContent/contentShow.html.twig', [
            'content'   => $content,
            'tarifs' => $tarifRepository->findAll()
        ]);
    }

    /**
     * @Route("/news", name="news_index")
     */
    public function newsIndex(ContentRepository $contentRepository, SiFileRepository $pictures)
    {


        return $this->render('news/index.html.twig', [
            'contents' => $contentRepository->findby(['contentType' => 2]),
            'pictures' => $pictures->findAll()
        ]);
    }


     /**
      * @Route("/news/{id}/details", name="news_details")
      */
    public function newsDetails(Content $content)
    {

        return $this->render('news/details.html.twig', [
            'content' => $content
        ]);
    }
}

templates/UserTemplate/userContent/_contentCover.html.twig
<div class="card bg-dark text-white border-0 ">
        {# titre #}
        {% if language == "en_EN" and content.titleEn is not null %}
            <h1 class=" d-md-none d-inline pl-2">{{content.titleEn}}</h1> 
        {% else %}
                <h1 class=" d-md-none d-inline pl-2">{{content.titleFr}}</h1>
        {% endif %}
        {# banniere #}
        <img class="img-fluid" src="/upload/file/{% if content.cover.mediaFileName is defined %}{{content.cover.mediaFileName }}
                                {% else %}blackCover.jpg
                                {% endif %}"
            class="imgTop img-fluid" alt="show photo" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            {# titre #}
            {% if language == "en_EN" and content.titleEn is not null %}
            <h1 class="card-title pt-4 mt-4 d-none d-md-block"> {{ content.titleEn }} </h1>
        {% else %}
            <h1 class="card-title pt-4 mt-4 d-none d-md-block"> {{ content.titleFr }} </h1>
        {% endif %}
            {% if content.author is not null %}
                <h4 class="card-text p-0 mt-1 d-none d-md-block"> {% trans into language %}De{% endtrans %} : {{ content.author }} </h4>
            {% endif %}
            {% if content.author is not null %}
                <h4 class="card-text p-0 mt-1 d-none d-md-block"> {% trans into language %}Mise en scène{% endtrans %} : {{ content.director }} </h4>
            {% endif %}
        </div>
    </div>

templates/UserTemplate/userContent/_contentEcho.html.twig
        {% if content.enEcho|length > 0 %}
<div class=" container pb-3 ">
    <hr class="m-0">
    <!-- "mais aussi" pill -->
    <div class="p-0 m-auto redPill">
        <p class="redPill">mais aussi...</p>
    </div>
    
    <div class="row">
            {% for relativeContent in content.enEcho %}
                <div class="col-4">
                    <div class="card">
                        <img src="/upload/file/{{relativeContent.thumbnail.mediaFileName}}" class="card-img-top" alt="{{relativeContent.titleFr}}">
                        <div class="card-body">
                            <h5 class="card-title">{{relativeContent.titleFr}}</h5>
                            <p class="card-text">{{relativeContent.contentTypeName}}</p>
                            <p class="card-text">{{relativeContent.titleFr}}</p>
                            <a href="{{ path('show_content', {'slug': relativeContent.slug}) }}" class="btn btn-primary">En savoir plus</a>
                        </div>
                    </div>
                    
                </div>
            {% endfor%}
    </div>
</div>
        {% endif %}

templates/UserTemplate/userContent/_contentInfospratiques.html.twig
{% if content.duree is not null  or content.lieu is not null or content.note is not null %}
	<div class="bg-secondary p-2 text-light">
{% if content.duree is not null %}
	<p>{% trans into language %}Durée{% endtrans %} : <strong>{{content.duree}}</strong></p>
{% endif %}

{% if content.lieu is not null %}
	<p>{% trans into language %}Lieu{% endtrans %} : <strong>{{content.lieu}}</strong></p>
{% endif %}

{% if content.note is not null %}
		<p>{% trans into language %}A noter{% endtrans %}	 : <strong>{{content.note|raw}}</strong></p>
{% endif %}
		</div>
{% endif %}
		

templates/UserTemplate/userContent/_contentLogoCountry.html.twig
<div class="row m-0">
            <div class="col-md-3 p-0">               
                <div class=" mr-4 d-flex align-items-center redPill">
                        {# country #}
                    {% if language == "en_EN" and content.CountryEn is not null %}
                        <p class="m-auto px-1 d-block">{{content.countryEn}}</p> 
                    {% else %}
                    <p class="m-auto px-1 d-block">{{content.countryFr}}</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-9 row">
            {% if content.themes|length > 0 %}
                {% for theme in content.themes %}
                    <div class=" col-4 col-md-3">
                        <img src="/upload/file/{{ theme.picture.mediaFileName }}" class="img-fluid"   alt="">
                    </div>
                {% endfor %}
            {% endif %}                
            </div>
        </div>

templates/UserTemplate/userContent/_contentPartnerLogos.html.twig
<div class="d-flex flex-md-column align-items-md-center">
{% for logo in content.logos %}
<img src="/upload/file/{{logo.mediaFileName}}" alt="{{logo.name}}" class="img-fluid py-3" >
{% endfor %}
</div>

templates/UserTemplate/userContent/_contentPictures.html.twig
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
    {% for picture in content.pictures %}
    <div class="carousel-item {%if loop.index == 1 %} active {%endif%}">
      <img src="/upload/file/{{ picture.mediaFileName }}" class="d-block w-100 " alt="show photo"/>
    </div>
    {% endfor %}
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

templates/UserTemplate/userContent/_contentRepesentations.html.twig
{% if content.sessions|length > 0  %}
	<table class="table representations">
		<thead>
			<tr>
				<th class="px-1">Date de représentation</th>
				<th class="px-1">Lieu</th>
				<th class="px-1">Tarifs</th>
				<th class="px-1">Réservation</th>
			</tr>
		</thead>
		<tbody>
			{% for session in content.sessions %}
				<tr>
					<td class="px-1">{{ session.sessionDate ? session.sessionDate|date('d-m-Y à H:i') : '' }}</td>
					<td class="px-1">{{ session.location }}</td>
					<td class="px-1">
					{% for tarif in session.tarifs %}
						<a href="#" data-toggle="modal" data-target="#TarifModal">{{tarif.grille}}</a>
					{% endfor %}
					</td>
					<td class="px-1"> <a href="{{session.mapadoLink}}">Billetterie</a>

					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>


<!-- Modal Tarifs -->
<div class="modal fade bd-example-modal-lg" id="TarifModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Grille tarifaire</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>

			<div class="container modalTarif">
				<div>
					<table class="tarifTable">
						<tr>
							<th class="noBorder"></th>
							{% for tarif in tarifs %}
							<th class="tarifName">Tarif {{ tarif.grille }}</th>
							{% endfor %}
						</tr>
						<tr>
							<th class="TarifTitle">Pass Festival</th>
							{% for tarif in tarifs %}
								<td>{{ tarif.PassFestival }} €</td>
							{% endfor %}
						</tr>
						<tr>
							<th class="TarifTitle">Pass Festivals -28 ans**</th>
							{% for tarif in tarifs %}
								<td>{{ tarif.PassJeune }} €</td>
							{% endfor %}
						</tr>
					</table>

					<br>

					<table class="tarifTable">
						<tr>
							<th class="noBorder"></th>
							{% for tarif in tarifs %}
								<th class="tarifName">Tarif {{ tarif.grille }}</th>
							{% endfor %}
						</tr>
						<tr>
							<th class="TarifTitle">Plein tarif</th>
							{% for tarif in tarifs %}
								<td>{{ tarif.pleinTarif }} €</td>
							{% endfor %}
						</tr>
						<tr>
							<th class="TarifTitle">Tarif réduit*</th>
							{% for tarif in tarifs %}
								<td>{{ tarif.reduce }} €</td>
							{% endfor %}
						</tr>
						<tr>
							<th class="TarifTitle">Jeunes -28 ans**</th>
							{% for tarif in tarifs %}
								<td>{{ tarif.jeune }} €</td>
							{% endfor %}
						</tr>
						<tr>
							<th class="TarifTitle">Bénéficiaires du RSA**</th>
							{% for tarif in tarifs %}
								<td>{{ tarif.RSA }} €</td>
							{% endfor %}
						</tr>
					</table>
					<p>* Abonnés ou adhérents des théâtres partenaires, +65 ans, familles nombreuses, demandeurs d'emploi,
						personnes handicapés, groupes (+10 personnes), sur présentation d'un justificatif.</p>
					<p>** Sur présentation d'un justificatif.</p>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Modal Tarifs -->

{% endif %}

templates/UserTemplate/userContent/contentShow.html.twig
{% extends 'base.html.twig' %}

{% set session = app.session.get('session') %}
{% if session['language'] is not defined %}
{% set language = "fr" %}
{% else %}
{% set language = session['language'] %}
{% endif %}

{% block title %}{% endblock %}
{% block body %}
<div class="container-fluid p-0">
                {# Image de couverture avec le titre #}
    {% include 'UserTemplate//userContent/_contentCover.html.twig' %}

    <div class="container p-0">
                {# pays et logo des themes du spectacle #}
        {% include 'UserTemplate//userContent/_contentLogoCountry.html.twig' %}
    </div>
    
    <div class="container px-0 pb-2">
        <div class=" row p-0 m-0">
            <div class=" {# Bloc du contenu enrichi #}
            {% if content.pictures|length > 0 %} col-md-6 
            {% else %} col-md-11 {% endif %} col-12"> 
                <div class="px-0 "> {# Bloc des infos pratiques #}
                    {% include 'UserTemplate//userContent/_contentInfospratiques.html.twig' %}
                </div>
                <div class="pre-scrollable px-2 pr-3 px-md-0 mt-2">
                {% if language == "en_EN" and content.contentEn is not null %}
                    {{content.contentEn|raw}}
                {% else %}
                    {{content.contentFr|raw}}
                {% endif %}
                </div>
            </div>
            
            {% if content.pictures|length > 0 %}
            <div class="col-md-5 pl-0 pr-1"> {# Bloc des illustrations du contenu #}             
                {% include 'UserTemplate//userContent/_contentPictures.html.twig' %}
            </div>
        {% endif %}
            
            <div class="col-md-1 px-1 px-md-0 "> {# Bloc des logos partenaires du spectacle #}             
                {% include 'UserTemplate//userContent/_contentPartnerLogos.html.twig' %}
            </div>

            <div class="col-12 mt-2 px-0">{# Bloc des représentations #}
                {% include 'UserTemplate//userContent/_contentRepesentations.html.twig' %}
            </div>

        </div>
    </div>

    {# Bloc des contenus en écho #}
    {% include 'UserTemplate//userContent/_contentEcho.html.twig' %}
</div>
{% endblock %}